### PR TITLE
Fix for Ruby 2.7 and newer versions and general update

### PR DESCRIPTION
**Pull request by alejandroperea**
This PR does a general update of the gem.

First of all, it requires in the `.ruby-version` the latest active version of Ruby 2.7 series, fixing the gem for 2.7 and superior applying @drukepple fix: https://github.com/18Months/themoviedb-api/issues/20#issuecomment-956378024

- Updates VCR cassettes
- Updates bundler to version 2
- Updates gems, development and runtime dependencies to the latest versions
- Removes `Tmdb::Search.list` as it is not working anymore in TMDb (removed from the API documentation): https://www.themoviedb.org/talk/593409e3c3a36859ef01eddb?language=gl-ES (maintainer says to be restored soon but it didn't happen)
- Fixes `Tmdb::Find.tv_episode` using a nowadays valid ID for generating a good VCR cassette

### CODE REVIEW

**Comment by alejandroperea** [comment]
@druzn3k I've been checking and the last merge was two years ago. Do you mind if I continue this gem under a organization of mine giving to 18Months, of course, the credits?

**Comment by druzn3k** [comment]
I'm in the process of doing just about that and I would love some help, if you wish to partecipate. I will probably do that between December and January. There is a lot of work that can be done, performance and ergonomics wise I think

**Comment by alejandroperea** [comment]
Sure! If I can help with something, let me know 👍

**Comment by druzn3k** [comment]
Still on board @alejandroperea ?

**Comment by alejandroperea** [comment]
Yes, let me know if I can help somehow!

**Comment by druzn3k** [comment]
Write me, my mail is m dot delcorno at 18months dot com, will figure out a plan of action :)

**Comment by alejandroperea** [comment]
Screenshot 2023-01-10 at 13 48 57

It seems it is not working 🤔  Can you see a typo?

**Comment by druzn3k** [comment]
Is dot it, not com. I'm a dumbass. For writing it stealthy I made a mess. Sorry :(

**Comment by druzn3k** [comment]
Ok, it seems all good. for now on, Don't change the version number please.

**Pull request merged**
